# Generated by Django 3.1.3 on 2020-11-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('prioridad', models.IntegerField(default=0)),
                ('imagen', models.ImageField(null=True, upload_to='media/')),
                ('peso', models.FloatField(default=0.0)),
                ('se_mide_en_reps', models.BooleanField(default=True)),
                ('intensidad_normal', models.IntegerField(default=0)),
                ('intensidad_falla', models.IntegerField(default=0)),
                ('categorias', models.ManyToManyField(to='workout.Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, max_length=500)),
                ('fecha_de_creacion', models.DateTimeField(auto_now_add=True)),
                ('favorito', models.BooleanField(default=False)),
                ('ejercicios', models.ManyToManyField(to='workout.Ejercicio')),
            ],
        ),
    ]
